name: CloudSync-Actions

on:
  push:
    branches:
      - master
  schedule:
    - cron: 20 3 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: CloudSync-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Rclone-Install
        run: wget 'https://raw.githubusercontent.com/wekingchen/my-file/master/rclone/rclone.zip' --no-check-certificate && sudo unzip rclone.zip && sudo chmod a+x rclone && sudo rm -f rclone.zip
      - name: Rclone-Config
        env:
          CLOUDSYNC_RCLONE_CONFIG: ${{ secrets.CLOUDSYNC_RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $CLOUDSYNC_RCLONE_CONFIG
          EOF
      - name: Rclone-Run
        run: |
          # Rclone-Run

          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }

          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 1

          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          ./rclone sync --user-agent  "NONISV|Microsoft|Microsoft OneDrive for Windows/22.065.0327.0002" GoogleDrive: OneDrive: -vv --stats-one-line --stats=5s --fast-list --delete-during --transfers 10 --checkers 20 --vfs-read-chunk-size 128M --buffer-size 256M --vfs-read-chunk-size-limit off --local-no-check-updated --drive-acknowledge-abuse --drive-keep-revision-forever  
          echo "Google文件已备份到Onedrive盘!"

      # - name: Delete workflow runs
      #   uses: GitRML/delete-workflow-runs@main
      #   with:
      #     retain_days: 7
      #     keep_minimum_runs: 550
          
