name: CloudSync-Actions

on:
  push:
    tags:
    - 'v*'
 #   branches:
 #     - master
  schedule:
    - cron: 0 */6 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: CloudSync-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Rclone-Install
        run: wget 'http://fgw2world.tk/frp/rclone' --no-check-certificate && sudo chmod a+x rclone
      - name: Rclone-Config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: Rclone-Run
        run: |
          # Rclone-Run

          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }

          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 1

          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          ./rclone sync -v weking_dropbox: weking_edu:Dropbox
          echo "Dropbox文件已备份到Google盘"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/20.114.0607.0002" -v weking_doc: weking_edu:OneDrive
          echo "weking_doc文件已备份到Google盘"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/20.114.0607.0002" -v weking_doc: weking_docbak:
          echo "weking_doc文件已备份到OneDrive盘"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/20.114.0607.0002" -v weking_edu: weking_spare:/spare
          echo "weking_edu文件已备份到OneDrive备用盘"
          ./rclone sync -v weking_edu: weking_edubak:
          echo "weking_edu文件已备份到Google备用盘"

🌓
