name: PanSync-Actions

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */4 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: PanSync-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Rclone-Install
        run: wget 'https://raw.githubusercontent.com/wekingchen/my-file/master/rclone/rclone.zip' --no-check-certificate && sudo unzip rclone.zip && sudo chmod a+x rclone && sudo rm -f rclone.zip
      - name: Rclone-Config
        env:
          PANSYNC_RCLONE_CONFIG: ${{ secrets.PANSYNC_RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $PANSYNC_RCLONE_CONFIG
          EOF
      - name: Rclone-Run
        run: |
          # Rclone-Run

          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }

          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 1

          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/21.073.0411.0002" -v pan: tj_s:/media
          echo "同济SharePoint影视文件同步完毕"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/21.073.0411.0002" -v pan: sharepoint_cn:/media
          echo "sharepoint_cn影视文件同步完毕"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/21.073.0411.0002" -v pan: sust_sharepoint:/media
          echo "陕西科技大学sharepoint影视文件同步完毕"
          ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/21.073.0411.0002" -v tj_s: sharepoint_cn:
          echo "同济SharePoint到sharepoint_cn的文件同步完毕"
          # ./rclone sync --user-agent "NONISV|Microsoft|Microsoft OneDrive for Windows/21.073.0411.0002" -v tj_s: sust_sharepoint:
          # echo "同济SharePoint到陕西科技大学SharePoint的文件同步完毕"
          ./rclone lsd tj_o:
          echo "同济OneDrive保活刷新完毕"
          ./rclone lsd tongji_golden:
          echo "同济golden SharePoint保活刷新完毕"
          ./rclone copy ~/.config/rclone/rclone.conf weking_dropbox:PrivateDoc/rclone/PanSync
          echo "rclone配置档备份完毕"
