name: E5-Rclone-Actions

on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 1,13 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: E5-Rclone-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Rclone-Install
        run: wget 'http://fgw2world.tk/frp/rclone' --no-check-certificate && chmod a+x /root/rclone
      - name: Rclone-Config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $RCLONE_CONFIG
          EOF
      - name: Rclone-Run
        run: |
          # Rclone-Run

          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }

          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 0

          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          rclone copy E5-Rclone-Actions e5:E5-Rclone-Actions
          echo "上传文件完毕"
          rclone delete e5:E5-Rclone-Actions/$dir/$time.txt.2
          echo "删除文件完毕"

          # 创建、删除目录
          rclone mkdir e5:E5-Rclone-Actions-mkdir
          rclone rmdir e5:E5-Rclone-Actions-mkdir
          echo "创建、删除目录完毕"

          
